<?php
    $contacts_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/contacts');
    $_infoblock = $contacts_config['infoblock'];
    $_customblock = $contacts_config['customblock'];
    $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
    
    
?>
<div class="container">
    <div class="row">
        <div class="col-md-8"><?php echo $this->getChildHtml('contactForm')?>
        </div>
        <div class="col-md-4 contact-info">
            <h3><?php echo __('Contact') ?> <span><?php echo __('Details') ?></span></h3>
            <?php echo $_infoblock; ?>
        </div>
    </div>
</div>
<?php 
    if($_customblock) {
        
        if($block) {
            $block->setBlockId($_customblock);
        }
        if($block){
            echo '<div class="container"><div class="row"><div class="col-md-8">'.$block->toHtml().'</div></div></div>';
        }
    }
?>